# Generated by Django 6.0.3 on 2026-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestroproducto',
            name='precio_ultimo',
        ),
        migrations.AddField(
            model_name='maestroproducto',
            name='zona',
            field=models.CharField(default='General', help_text='Ej: Frutería, Carnicería, Limpieza', max_length=100),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='color_hex',
            field=models.CharField(default='#0a8f34', max_length=7),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
