# Generated by Django 6.0.3 on 2026-04-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_itemlista_creado_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listacompra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maestroproducto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_maestros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tienda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maestroproducto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maestroproducto',
            name='zona',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='maestroproducto',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='tienda',
            unique_together={('usuario', 'nombre')},
        ),
    ]
