# Generated by Django 6.0.3 on 2026-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tienda_favorita',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar_icon',
            field=models.CharField(default='👤', max_length=20),
        ),
    ]
